### ISSUE TITLE
[Suggestion] Increase the probability of citizens' rumors being true

### ISSUE THREAD

**Issue by cpzjunior** [Secrets-of-Sosaria/World#150]
Currently, the biggest difficulty in the late game in my opinion is completing quests. Players, with their builds completed and better quality weapons and armor, start looking for items from epic character quests or end game quests, such as the balance quest, codex quest, titan quest, etc. However, these quests practically force players to clear all the dungeons in the game, even daily, since half of the rumors from the citizens of the cities are false and other rumor systems, such as the rat from Britain Castle, are so hidden that most players don't even know they exist. Players who choose to search for information through the citizens' rumors take months to complete a quest that should be much easier to complete, since it's just a matter of them knowing where the item is. My suggestion is to increase the probability of these rumors being true, in order to reward the effort of the player who goes through all the cities in the game in search of this information. I believe that something like 80% would be enough to change this dynamic, but I think any value above 50% is perfectly reasonable.

**Comment by EstelMatiazi** [comment]
I personally never engage with the rumor system because if something had a 50% chance of wasting my time I could just brute force my way through dungeons and have a somewhat similar success rate as I would if I was scouring cities in search of rumors. 

I think that if npcs had a range (from 40 to 80 or something) % for a truthful rumor I would try to engage with the system more.

**Comment by EstelMatiazi** [comment]
a fix has been merge into the repo, please close this issue.

**Comment by cpzjunior** [comment]
Ok, I'm closing the issue, thanks.
